dependencies:
  flutter:
    sdk: flutter
  # UI & Maps
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^1.0.0
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_database: ^10.4.0
  # Logic & API
  geolocator: ^10.1.0
  http: ^1.1.0
  provider: ^6.1.1 # Hoặc GetX/Bloc tùy chọn
  permission_handler: ^11.0.1